### ISSUE TITLE
color menu does not appear

### ISSUE THREAD

**Issue by psiquiatraa** [casey-c/sts_betterpaths#2]
the color menu of the mod does not appear on my screen. also, the selected nodes appear to be out of scale. do I have to use a specific video setting for the mod to work properly?

**Comment by casey-c** [comment]
Hi - sorry I never got to this when you posted about it a few weeks back. There are definitely some resolution bugs that I never fixed. This project is a bit dead at the moment (I was working on a sequel / replacement mod for it, but that is mostly halted as well as I have too many things to work on and too little time). I recommend using the highlight paths mod on the workshop (made by someone else), as that should work a bit better than this ugly hunk of broken junk. I apologize I didn't get a chance to respond earlier.

**Comment by psiquiatraa** [comment]
thank you for taking your time to answer me. I love seeing your mod on STS it looks so elegant. But anyway, I'll take your suggestion and use the workshop mod. thanks again
